config/routes.rb
Rails.application.routes.draw do
 root to: "static_pages#index"

 get "sign_in" => "static_pages#sign_in"
 get "sign_up" => "static_pages#sign_up"
 get "guest" => "sessions#guest"

 resource :sessions, only: [:new, :create, :destroy]

 resources :users, only: [:new, :create]

 namespace :api, defaults: {format: :json} do
  resources :sessions, only: [:create, :destroy]
  get "guest" => "sessions#guest"
  
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  resource :followings, only: [:create, :destroy]

  resources :tracks
  get "tracks/track_url/:id" => "tracks#track_url"

  resources :comments, only: [:index, :create, :edit, :update, :destroy]

  resources :likes, only: [:create, :destroy]
  get "user_likes" => "likes#user_index"

  resources :playlists, only: [:create, :show, :update, :destroy]
  get "user_playlists" => "playlists#user_playlists"
  post "playlists/add_track" => "playlists#add_track_to_playlist"
  delete "playlists/remove_track" =>
         "playlists#remove_track_from_playlist"

  get "feeds/user" => "feeds#dashboard_feed"
  get "feeds/explore" => "feeds#explore_feed"

  get "search" => "searches#search"
 end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    render :index
  end

  def sign_in
    render :sign_in
  end

  def sign_up
    render :sign_up
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<div id="errors"></div>
<div id="content"></div>

app/views/static_pages/sign_in.html.erb
<div id="navbar" class="sign-in-sign-up" style="padding: 20px 0"></div>
<div class="col-md-6 col-md-offset-3"
  <div class="navbar">
    <ul class="nav nav-tabs">
      <li class="navbar-right" style="border-bottom:1px solid lightgray;background: white">
        <a href="/" style="background:white">
          <strong style="background:white;color: black">TrackieChan</strong>
        </a>
      </li>
      <li>
        <a href="#sign_up" data-toggle="tab">Create an Account</a>
      </li>
      <li class="active">
        <a href="#sign_in" data-toggle="tab">
          Sign In
        </a>
      </li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane" id="sign_up">
        <!-- <h2>Create an Account</h2> -->
        <br>
        <form action="/users" method="POST">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

          <label for="username">Username</label><br>
          <input type="text" 
                 name="user[username]"
                 class="form-control"/><br>

          <label for="email">Email</label><br>
          <input type="text" 
                 name="user[email]"
                 class="form-control"/><br>

          <label for="password">Password</label><br>
          <input type="password" 
                 name="user[password]"
                 class="form-control"/><br>

          <label for="password">Password Confirmation</label><br>
          <input type="password" 
                 name="user[password_confirmation]"
                 class="form-control"/><br>

          <input type="submit" 
                 value="Create an Account!" 
                 class="btn btn-primary"/>
          &nbsp;
          <%= link_to "Guest Login", guest_url, class: "btn btn-default"%><br>
        </form>
      </div>
      <div class="tab-pane active" id="sign_in">
        <!-- <h2>Sign in</h2> -->
        <br>
        <form action="/sessions" method="POST">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

          <label for="username">Email</label><br>
          <input type="text" 
                 name="user[email]"
                 class="form-control"/><br>

          <label for="password">Password</label><br>
          <input type="password" 
                 name="user[password]"
                 class="form-control"/><br>

          <input type="submit" value="Sign In!" class="btn btn-primary"/>
          &nbsp;
          <%= link_to "Guest Login", guest_url, class: "btn btn-default"%>
          <br>

        </form>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/sign_in_sign_up.html.erb
<div id="content"></div>
<div class="col-md-6 col-md-offset-3"
  <div class="navbar">
    <ul class="nav nav-tabs">
      <li class="navbar-right" style="border-bottom:1px solid lightgray;background: white">
        <a style="background:white">
          <strong style="background:white;color: black">TrackieChan</strong>
        </a>
      </li>
      <li class="active">
        <a href="#sign_up" data-toggle="tab">Create an Account</a>
      </li>
      <li><a href="#sign_in" data-toggle="tab">Sign In</a></li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="sign_up">
        <!-- <h2>Create an Account</h2> -->
        <form action="/users" method="POST">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

          <label for="username">Username</label><br>
          <input type="text" 
                 name="user[username]"
                 class="form-control"/><br>

          <label for="email">Email</label><br>
          <input type="text" 
                 name="user[email]"
                 class="form-control"/><br>

          <label for="password">Password</label><br>
          <input type="password" 
                 name="user[password]"
                 class="form-control"/><br>

          <label for="password">Password Confirmation</label><br>
          <input type="password" 
                 name="user[password_confirmation]"
                 class="form-control"/><br>

          <input type="submit" 
                 value="Create an Account!" 
                 class="btn btn-primary"/><br>
        </form>
      </div>
      <div class="tab-pane" id="sign_in">
        <!-- <h2>Sign in</h2> -->
        <form action="/sessions" method="POST">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

          <label for="username">Email</label><br>
          <input type="text" 
                 name="user[email]"
                 class="form-control"/><br>

          <label for="password">Password</label><br>
          <input type="password" 
                 name="user[password]"
                 class="form-control"/><br>

          <input type="submit" value="Login!" class="btn btn-primary"/><br>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  React.render(
    React.createElement(Navbar),
    document.getElementById("content")
  )
</script>

app/views/static_pages/sign_up.html.erb
<div id="navbar" class="sign-in-sign-up" style="padding: 20px 0"></div>
<div class="col-md-6 col-md-offset-3"
  <div class="navbar">
    <ul class="nav nav-tabs">
      <li class="navbar-right" style="border-bottom:1px solid lightgray;background: white">
        <a href="/" style="background:white">
          <strong style="background:white;color: black">TrackieChan</strong>
        </a>
      </li>
      <li class="active">
        <a href="#sign_up" data-toggle="tab">Create an Account</a>
      </li>
      <li><a href="#sign_in" data-toggle="tab">Sign In</a></li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active" id="sign_up">
        <!-- <h2>Create an Account</h2> -->
        <br>
        <form action="/users" method="POST">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

          <label for="username">Username</label><br>
          <input type="text" 
                 name="user[username]"
                 class="form-control"/><br>

          <label for="email">Email</label><br>
          <input type="text" 
                 name="user[email]"
                 class="form-control"/><br>

          <label for="password">Password</label><br>
          <input type="password" 
                 name="user[password]"
                 class="form-control"/><br>

          <label for="password">Password Confirmation</label><br>
          <input type="password" 
                 name="user[password_confirmation]"
                 class="form-control"/><br>

          <input type="submit" 
                 value="Create an Account!" 
                 class="btn btn-primary"/>
          &nbsp;
          <%= link_to "Guest Login", guest_url, class: "btn btn-default"%><br>
        </form>
      </div>
      <div class="tab-pane" id="sign_in">
        <!-- <h2>Sign in</h2> -->
        <br>
        <form action="/sessions" method="POST">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">

          <label for="username">Email</label><br>
          <input type="text" 
                 name="user[email]"
                 class="form-control"/><br>

          <label for="password">Password</label><br>
          <input type="password" 
                 name="user[password]"
                 class="form-control"/><br>

          <input type="submit" value="Sign In!" class="btn btn-primary"/>
          &nbsp;
          <%= link_to "Guest Login", guest_url, class: "btn btn-default"%><br>
        </form>
      </div>
    </div>
  </div>
</div>