config/routes.rb
Rails.application.routes.draw do
 root to: "static_pages#index"

 get "sign_in" => "static_pages#sign_in"
 get "sign_up" => "static_pages#sign_up"
 get "guest" => "sessions#guest"

 resource :sessions, only: [:new, :create, :destroy]

 resources :users, only: [:new, :create]

 namespace :api, defaults: {format: :json} do
  resources :sessions, only: [:create, :destroy]
  get "guest" => "sessions#guest"
  
  resources :users, only: [:create, :show, :edit, :update, :destroy]

  resource :followings, only: [:create, :destroy]

  resources :tracks
  get "tracks/track_url/:id" => "tracks#track_url"

  resources :comments, only: [:index, :create, :edit, :update, :destroy]

  resources :likes, only: [:create, :destroy]
  get "user_likes" => "likes#user_index"

  resources :playlists, only: [:create, :show, :update, :destroy]
  get "user_playlists" => "playlists#user_playlists"
  post "playlists/add_track" => "playlists#add_track_to_playlist"
  delete "playlists/remove_track" =>
         "playlists#remove_track_from_playlist"

  get "feeds/user" => "feeds#dashboard_feed"
  get "feeds/explore" => "feeds#explore_feed"

  get "search" => "searches#search"
 end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url%>">TrackieChan</a>
    </div>


    <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Logout", sessions_url, 
                          class: "btn btn-danger",
                          method: :delete %></li>
        <% else %>
          <li><%= link_to "Create an Account", 
                          new_user_url,
                          {class: "btn btn-default"} %></li>
          <li><%= link_to "Login", new_sessions_url,
                          {class: "btn btn-default"} %></li>
        <% end %>        
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrackieChan</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "#{root_url}/favicon.ico" %>
  <link href='https://fonts.googleapis.com/css?family=Pacifico|Varela+Round' rel='stylesheet' type='text/css'>
</head>
<body>
  <% if current_user %>
    <script type="text/javascript">
      var userId = "<%= current_user.id %>";
      localStorage.setItem("user", btoa(btoa(userId)));
      window.CLOUDINARY_NAME = "q32rnq9jfaskfaskfasf";
      window.CLOUDINARY_PRESET = "f0qeyyhf";
      window.CLOUDINARY_VERSION = "v1_1";
    </script>
  <% else %>
    <script type="text/javascript">
      localStorage.removeItem("user");
      window.CLOUDINARY_NAME = "q32rnq9jfaskfaskfasf";
      window.CLOUDINARY_PRESET = "f0qeyyhf";
      window.CLOUDINARY_VERSION = "v1_1";
    </script>
  <% end %>
  
  <div class="container flash">
    <% flash.each do |type, message|%>
      <div class="container alert-<%= type.to_s %>">
        <% if message.is_a? Array %>
          <% message.each do |m| %>
            <%= m %><br/>
          <% end %>
        <% else %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>